[[locations]]
file = "pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/oefp/__init__.py"
type = "python-dunder"

[[locations]]
file = "python/oefp/__init__.py"
type = "python-version-info"

[[locations]]
file = "CMakeLists.txt"
type = "cmake-project"

[[locations]]
file = "include/oefp/oefp.h"
type = "c-define"
prefix = "OEFP"

[[locations]]
file = "swig/oefp.i"
type = "c-define"
prefix = "OEFP"

[[locations]]
file = "tests/python/test_oefp.py"
type = "custom"
template = 'oefp\.__version__ == "{version}"'
label = "test-version-string"

[[locations]]
file = "tests/python/test_oefp.py"
type = "custom"
template = 'oefp\.__version_info__ == \({info_tuple}\)'
label = "test-version-info"
