[[locations]]
file = "pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/oefp/__init__.py"
type = "python-dunder"

[[locations]]
file = "python/oefp/__init__.py"
type = "python-version-info"

[[locations]]
file = "CMakeLists.txt"
type = "cmake-project"

[[locations]]
file = "include/oefp/oefp.h"
type = "c-define"
prefix = "OEFP"

[[locations]]
file = "swig/oefp.i"
type = "c-define"
prefix = "OEFP"

[[locations]]
file = "swig/oefp.i"
type = "custom"
template = '__version__ = "{version}"'
label = "swig-python-version"

[[locations]]
file = "docs/conf.py"
type = "custom"
template = 'release = "{version}"'
label = "docs-release"

[[locations]]
file = "docs/conf.py"
type = "custom"
template = 'version = "{major}\.\d+"'
label = "docs-version-major"

[[locations]]
file = "docs/conf.py"
type = "custom"
template = 'version = "\d+\.{minor}"'
label = "docs-version-minor"
