"""Generate kallisto parameter tables as C++ data arrays.

kallisto (Apache 2.0, AstraZeneca; Caldeweyher, Meli, Pracht) atomic parameter
tables ported verbatim for use in OEFP (MIT). This script imports kallisto's
data module and emits C++ constexpr arrays in namespace OEFP::kallisto.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

EXPECTED_KALLISTO_VERSION = "1.0.10"


def _verify_kallisto() -> None:
    """Guard against unexpected kallisto version to preserve deterministic output."""
    import kallisto

    version = str(kallisto.__version__)
    if version != EXPECTED_KALLISTO_VERSION:
        raise RuntimeError(
            f"Expected kallisto {EXPECTED_KALLISTO_VERSION}, imported {version!r}."
        )


def _emit_cpp_array_1d(name: str, data: Any, dtype: str, is_string_array: bool = False) -> list[str]:
    """Emit a 1D C++ const array."""
    lines = []
    length = len(data)
    if is_string_array:
        # For string arrays, emit as const char* ARRAY[] (not const const char*)
        lines.append(f"const char* const {name}[{length}] = {{")
    else:
        lines.append(f"const {dtype} {name}[{length}] = {{")

    # Emit in rows of 4 values for readability
    values = [data[i] for i in range(length)]
    for i in range(0, length, 4):
        chunk = values[i:i+4]
        if is_string_array:
            # String array
            formatted = ", ".join(f'"{v}"' for v in chunk)
        else:
            # Numeric array
            formatted = ", ".join(str(v) for v in chunk)
        lines.append(f"    {formatted},")

    lines.append("};")
    return lines


def _emit_cpp_array_2d(name: str, data: Any, dtype: str, dim1: int, dim2: int) -> list[str]:
    """Emit a 2D C++ const array."""
    lines = []
    lines.append(f"const {dtype} {name}[{dim1}][{dim2}] = {{")

    for i in range(dim1):
        row_values = [data[i][j] for j in range(dim2)]
        formatted = ", ".join(str(v) for v in row_values)
        lines.append(f"    {{{formatted}}},")

    lines.append("};")
    return lines


def _emit_cpp_array_3d(name: str, data: Any, dtype: str, dim1: int, dim2: int, dim3: int) -> list[str]:
    """Emit a 3D C++ const array."""
    lines = []
    lines.append(f"const double {name}[{dim1}][{dim2}][{dim3}] = {{")

    for i in range(dim1):
        lines.append("    {")
        for j in range(dim2):
            row_values = [data[i][j][k] for k in range(dim3)]
            formatted = ", ".join(str(v) for v in row_values)
            lines.append(f"        {{{formatted}}},")
        lines.append("    },")

    lines.append("};")
    return lines


def _generate_cpp_data(output: Path) -> None:
    """Generate the C++ data file src/kallisto_data.cpp."""
    import kallisto.data
    import kallisto.data.alpha
    import kallisto.data.vdw
    import kallisto.units

    _verify_kallisto()

    lines = [
        "// Generated by tests/python/generate_kallisto_data.py",
        "// DO NOT EDIT MANUALLY.",
        "//",
        "// Atomic parameter tables ported from kallisto (Apache 2.0):",
        "//   AstraZeneca; Caldeweyher, Meli, Pracht",
        "//   https://github.com/AstraZeneca/kallisto",
        f"// kallisto version: {EXPECTED_KALLISTO_VERSION}",
        "//",
        "// INDEXING CONVENTION:",
        "//   - All tables except chemical_symbols and vdw_* are indexed [Z-1]",
        "//     (kallisto native: element Z=1..86 stored at index 0..85)",
        "//   - chemical_symbols is indexed [Z] (length 119, index 0 = \"X\")",
        "//   - vdw_rahm and vdw_truhlar are Z-indexed [Z] (length 87, index 0 = sentinel)",
        "",
        '#include "oefp/kallisto_data.h"',
        "",
        "namespace OEFP {",
        "namespace kallisto {",
        "",
        f"// BOHR_RADIUS_ANGSTROM is defined inline in the header",
        "",
    ]

    # Covalent radii (length 118, Z-1 indexed)
    lines.append("// Covalent radii (Angstrom) [Z-1 indexed, length 118]")
    lines.extend(_emit_cpp_array_1d("COVALENT_RADIUS", kallisto.data.covalent_radius, "double"))
    lines.append("")

    # Pauling electronegativity (length 86, Z-1 indexed)
    lines.append("// Pauling electronegativity [Z-1 indexed, length 86]")
    lines.extend(_emit_cpp_array_1d("PAULING_EN", kallisto.data.pauling_en, "double"))
    lines.append("")

    # EEQ parameters (all length 86, Z-1 indexed)
    lines.append("// EEQ electronegativity [Z-1 indexed, length 86]")
    lines.extend(_emit_cpp_array_1d("EEQ_EN", kallisto.data.eeq_en, "double"))
    lines.append("")

    lines.append("// EEQ chemical hardness [Z-1 indexed, length 86]")
    lines.extend(_emit_cpp_array_1d("EEQ_GAMM", kallisto.data.eeq_gamm, "double"))
    lines.append("")

    lines.append("// EEQ CN factor [Z-1 indexed, length 86]")
    lines.extend(_emit_cpp_array_1d("EEQ_CNFAK", kallisto.data.eeq_cnfak, "double"))
    lines.append("")

    lines.append("// EEQ alpha parameter [Z-1 indexed, length 86]")
    lines.extend(_emit_cpp_array_1d("EEQ_ALP", kallisto.data.eeq_alp, "double"))
    lines.append("")

    # Chemical symbols (length 119, Z-indexed)
    lines.append("// Chemical symbols [Z indexed, length 119, index 0 = \"X\"]")
    lines.extend(_emit_cpp_array_1d("CHEMICAL_SYMBOLS", kallisto.data.chemical_symbols, "", is_string_array=True))
    lines.append("")

    # D4 polarizability parameters (kallisto.data.alpha)
    lines.append("// D4 reference polarizabilities: refn (integer counts) [Z-1 indexed, length 86]")
    refn_int = [int(x) for x in kallisto.data.alpha.refn]
    lines.extend(_emit_cpp_array_1d("D4_REFN", refn_int, "int"))
    lines.append("")

    lines.append("// D4 chemical hardness [Z-1 indexed, length 86]")
    lines.extend(_emit_cpp_array_1d("D4_GAM", kallisto.data.alpha.gam, "double"))
    lines.append("")

    lines.append("// D4 effective nuclear charge [Z-1 indexed, length 86]")
    zeff_int = [int(x) for x in kallisto.data.alpha.zeff]
    lines.extend(_emit_cpp_array_1d("D4_ZEFF", zeff_int, "int"))
    lines.append("")

    # 2D arrays (7 x 86)
    lines.append("// D4 reference CN [7 x 86, Z-1 indexed in 2nd dim]")
    lines.extend(_emit_cpp_array_2d("D4_REFX", kallisto.data.alpha.refx, "double", 7, 86))
    lines.append("")

    lines.append("// D4 reference hcount [7 x 86, Z-1 indexed in 2nd dim]")
    lines.extend(_emit_cpp_array_2d("D4_REFH", kallisto.data.alpha.refh, "double", 7, 86))
    lines.append("")

    lines.append("// D4 hydrogen count [7 x 86, Z-1 indexed in 2nd dim]")
    lines.extend(_emit_cpp_array_2d("D4_HCOUNT", kallisto.data.alpha.hcount, "double", 7, 86))
    lines.append("")

    lines.append("// D4 a-scale [7 x 86, Z-1 indexed in 2nd dim]")
    lines.extend(_emit_cpp_array_2d("D4_ASCALE", kallisto.data.alpha.ascale, "double", 7, 86))
    lines.append("")

    lines.append("// D4 reference CN [7 x 86, Z-1 indexed in 2nd dim]")
    lines.extend(_emit_cpp_array_2d("D4_REFCN", kallisto.data.alpha.refcn, "double", 7, 86))
    lines.append("")

    lines.append("// D4 reference system [7 x 86, Z-1 indexed in 2nd dim]")
    refsys_int = [[int(kallisto.data.alpha.refsys[i][j]) for j in range(86)] for i in range(7)]
    lines.extend(_emit_cpp_array_2d("D4_REFSYS", refsys_int, "int", 7, 86))
    lines.append("")

    # 3D array alphaiw (23 x 7 x 86)
    lines.append("// D4 atomic polarizabilities [23 x 7 x 86, Z-1 indexed in 3rd dim]")
    lines.extend(_emit_cpp_array_3d("D4_ALPHAIW", kallisto.data.alpha.alphaiw, "double", 23, 7, 86))
    lines.append("")

    # sscale (length 4, NOT 86 as the brief mistakenly says)
    lines.append("// D4 s-scale [length 4]")
    lines.extend(_emit_cpp_array_1d("D4_SSCALE", kallisto.data.alpha.sscale, "double"))
    lines.append("")

    # seciw (23 x 8)
    lines.append("// D4 secondary polarizabilities [23 x 8]")
    lines.extend(_emit_cpp_array_2d("D4_SECIW", kallisto.data.alpha.seciw, "double", 23, 8))
    lines.append("")

    # vdW radii (symbol-keyed dicts -> Z-indexed arrays)
    # Build Z-indexed arrays of length 87 (index 0 = sentinel, 1..86 populated)
    vdw_rahm = [0.0] * 87
    vdw_truhlar = [0.0] * 87
    for z in range(1, 87):
        symbol = kallisto.data.chemical_symbols[z]
        if symbol in kallisto.data.vdw.rahm:
            vdw_rahm[z] = kallisto.data.vdw.rahm[symbol]
        else:
            raise ValueError(f"Missing rahm entry for Z={z} ({symbol})")
        if symbol in kallisto.data.vdw.truhlar:
            vdw_truhlar[z] = kallisto.data.vdw.truhlar[symbol]
        else:
            raise ValueError(f"Missing truhlar entry for Z={z} ({symbol})")

    lines.append("// vdW Rahm radii (Angstrom) [Z indexed, length 87, index 0 = sentinel]")
    lines.extend(_emit_cpp_array_1d("VDW_RAHM", vdw_rahm, "double"))
    lines.append("")

    lines.append("// vdW Truhlar radii (Angstrom) [Z indexed, length 87, index 0 = sentinel]")
    lines.extend(_emit_cpp_array_1d("VDW_TRUHLAR", vdw_truhlar, "double"))
    lines.append("")

    lines.append("} // namespace kallisto")
    lines.append("} // namespace OEFP")
    lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")


def _generate_cpp_header(output: Path) -> None:
    """Generate the C++ header include/oefp/kallisto_data.h."""
    import kallisto.units

    lines = [
        "// Generated by tests/python/generate_kallisto_data.py",
        "// DO NOT EDIT MANUALLY.",
        "//",
        "// Atomic parameter tables ported from kallisto (Apache 2.0):",
        "//   AstraZeneca; Caldeweyher, Meli, Pracht",
        "//   https://github.com/AstraZeneca/kallisto",
        f"// kallisto version: {EXPECTED_KALLISTO_VERSION}",
        "//",
        "// All tables are defined as const globals in the implementation; this header",
        "// provides visibility to translation units that include it.",
        "",
        "#ifndef OEFP_KALLISTO_DATA_H",
        "#define OEFP_KALLISTO_DATA_H",
        "",
        "namespace OEFP {",
        "namespace kallisto {",
        "",
        "// Bohr radius in Angstrom (defined inline)",
        f"inline constexpr double BOHR_RADIUS_ANGSTROM = {kallisto.units.Bohr};",
        "",
        "// Covalent radii [Z-1 indexed, length 118]",
        "extern const double COVALENT_RADIUS[118];",
        "",
        "// Pauling electronegativity [Z-1 indexed, length 86]",
        "extern const double PAULING_EN[86];",
        "",
        "// EEQ parameters [Z-1 indexed, length 86]",
        "extern const double EEQ_EN[86];",
        "extern const double EEQ_GAMM[86];",
        "extern const double EEQ_CNFAK[86];",
        "extern const double EEQ_ALP[86];",
        "",
        "// Chemical symbols [Z indexed, length 119]",
        "extern const char* const CHEMICAL_SYMBOLS[119];",
        "",
        "// D4 polarizability parameters [Z-1 indexed except where noted]",
        "extern const int D4_REFN[86];",
        "extern const double D4_GAM[86];",
        "extern const int D4_ZEFF[86];",
        "extern const double D4_REFX[7][86];",
        "extern const double D4_REFH[7][86];",
        "extern const double D4_HCOUNT[7][86];",
        "extern const double D4_ASCALE[7][86];",
        "extern const double D4_REFCN[7][86];",
        "extern const int D4_REFSYS[7][86];",
        "extern const double D4_ALPHAIW[23][7][86];",
        "extern const double D4_SSCALE[4];",
        "extern const double D4_SECIW[23][8];",
        "",
        "// vdW radii [Z indexed, length 87]",
        "extern const double VDW_RAHM[87];",
        "extern const double VDW_TRUHLAR[87];",
        "",
        "} // namespace kallisto",
        "} // namespace OEFP",
        "",
        "#endif // OEFP_KALLISTO_DATA_H",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate kallisto parameter tables as C++ data arrays."
    )
    parser.add_argument("--output", type=Path, required=True,
                        help="Path to the output C++ source file (e.g., src/kallisto_data.cpp)")
    parser.add_argument("--header", type=Path, required=True,
                        help="Path to the output C++ header file (e.g., include/oefp/kallisto_data.h)")
    args = parser.parse_args()

    print(f"Generating kallisto data tables (version {EXPECTED_KALLISTO_VERSION})...")
    _generate_cpp_data(args.output)
    print(f"  Wrote {args.output}")
    _generate_cpp_header(args.header)
    print(f"  Wrote {args.header}")
    print("Done.")


if __name__ == "__main__":
    main()
