// Generated by tests/python/generate_kallisto_data.py
// DO NOT EDIT MANUALLY.
//
// Atomic parameter tables ported from kallisto (Apache 2.0):
//   AstraZeneca; Caldeweyher, Meli, Pracht
//   https://github.com/AstraZeneca/kallisto
// kallisto version: 1.0.10
//
// All tables are defined as const globals in the implementation; this header
// provides visibility to translation units that include it.

#ifndef OEFP_KALLISTO_DATA_H
#define OEFP_KALLISTO_DATA_H

namespace OEFP {
namespace kallisto {

// Bohr radius in Angstrom (defined inline)
inline constexpr double BOHR_RADIUS_ANGSTROM = 0.5291772105437147;

// Covalent radii [Z-1 indexed, length 118]
extern const double COVALENT_RADIUS[118];

// Pauling electronegativity [Z-1 indexed, length 86]
extern const double PAULING_EN[86];

// EEQ parameters [Z-1 indexed, length 86]
extern const double EEQ_EN[86];
extern const double EEQ_GAMM[86];
extern const double EEQ_CNFAK[86];
extern const double EEQ_ALP[86];

// Chemical symbols [Z indexed, length 119]
extern const char* const CHEMICAL_SYMBOLS[119];

// D4 polarizability parameters [Z-1 indexed except where noted]
extern const int D4_REFN[86];
extern const double D4_GAM[86];
extern const int D4_ZEFF[86];
extern const double D4_REFX[7][86];
extern const double D4_REFH[7][86];
extern const double D4_HCOUNT[7][86];
extern const double D4_ASCALE[7][86];
extern const double D4_REFCN[7][86];
extern const int D4_REFSYS[7][86];
extern const double D4_ALPHAIW[23][7][86];
extern const double D4_SSCALE[4];
extern const double D4_SECIW[23][8];

// vdW radii [Z indexed, length 87]
extern const double VDW_RAHM[87];
extern const double VDW_TRUHLAR[87];

} // namespace kallisto
} // namespace OEFP

#endif // OEFP_KALLISTO_DATA_H
