#include "oefp/rdkit_descriptors.h"

#include <array>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace OEFP {
namespace {

struct StaticRDKitDefinition {
    const char* name;
    DescriptorValueKind value_kind;
    const char* group;
    const char* source_type;
    const char* parameters;
    const char* description;
    const char* canonical_id;
    DescriptorPrerequisites prerequisites;
};

constexpr std::array<StaticRDKitDefinition, 214> kRDKitDefinitions{{
    {"MaxAbsEStateIndex", DescriptorValueKind::Float, "rdkit:EState", "EState", "", "MaxAbsEStateIndex", "", 0u},
    {"MaxEStateIndex", DescriptorValueKind::Float, "rdkit:EState", "EState", "", "MaxEStateIndex", "", 0u},
    {"MinAbsEStateIndex", DescriptorValueKind::Float, "rdkit:EState", "EState", "", "MinAbsEStateIndex", "", 0u},
    {"MinEStateIndex", DescriptorValueKind::Float, "rdkit:EState", "EState", "", "MinEStateIndex", "", 0u},
    {"qed", DescriptorValueKind::Float, "rdkit:Composite", "Composite", "", "qed", "", 0u},
    {"SPS", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "SPS", "", 0u},
    {"MolWt", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "MolWt", "", 0u},
    {"HeavyAtomMolWt", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "HeavyAtomMolWt", "", 0u},
    {"ExactMolWt", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "ExactMolWt", "", 0u},
    {"NumValenceElectrons", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumValenceElectrons", "", 0u},
    {"NumRadicalElectrons", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumRadicalElectrons", "", 0u},
    {"MaxPartialCharge", DescriptorValueKind::Float, "rdkit:PartialCharge", "PartialCharge", "", "MaxPartialCharge", "", 0u},
    {"MinPartialCharge", DescriptorValueKind::Float, "rdkit:PartialCharge", "PartialCharge", "", "MinPartialCharge", "", 0u},
    {"MaxAbsPartialCharge", DescriptorValueKind::Float, "rdkit:PartialCharge", "PartialCharge", "", "MaxAbsPartialCharge", "", 0u},
    {"MinAbsPartialCharge", DescriptorValueKind::Float, "rdkit:PartialCharge", "PartialCharge", "", "MinAbsPartialCharge", "", 0u},
    {"FpDensityMorgan1", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "FpDensityMorgan1", "", 0u},
    {"FpDensityMorgan2", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "FpDensityMorgan2", "", 0u},
    {"FpDensityMorgan3", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "FpDensityMorgan3", "", 0u},
    {"BCUT2D_MWHI", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_MWHI", "", 0u},
    {"BCUT2D_MWLOW", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_MWLOW", "", 0u},
    {"BCUT2D_CHGHI", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_CHGHI", "", 0u},
    {"BCUT2D_CHGLO", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_CHGLO", "", 0u},
    {"BCUT2D_LOGPHI", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_LOGPHI", "", 0u},
    {"BCUT2D_LOGPLOW", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_LOGPLOW", "", 0u},
    {"BCUT2D_MRHI", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_MRHI", "", 0u},
    {"BCUT2D_MRLOW", DescriptorValueKind::Float, "rdkit:BCUT2D", "BCUT2D", "", "BCUT2D_MRLOW", "", 0u},
    {"AvgIpc", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "AvgIpc", "", 0u},
    {"BalabanJ", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "BalabanJ", "", 0u},
    {"BertzCT", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "BertzCT", "", 0u},
    {"Chi0", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi0", "", 0u},
    {"Chi0n", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi0n", "", 0u},
    {"Chi0v", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi0v", "", 0u},
    {"Chi1", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi1", "", 0u},
    {"Chi1n", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi1n", "", 0u},
    {"Chi1v", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi1v", "", 0u},
    {"Chi2n", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi2n", "", 0u},
    {"Chi2v", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi2v", "", 0u},
    {"Chi3n", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi3n", "", 0u},
    {"Chi3v", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi3v", "", 0u},
    {"Chi4n", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi4n", "", 0u},
    {"Chi4v", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Chi4v", "", 0u},
    {"HallKierAlpha", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "HallKierAlpha", "", 0u},
    {"Ipc", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Ipc", "", 0u},
    {"Kappa1", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Kappa1", "", 0u},
    {"Kappa2", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Kappa2", "", 0u},
    {"Kappa3", DescriptorValueKind::Float, "rdkit:Connectivity", "Connectivity", "", "Kappa3", "", 0u},
    {"LabuteASA", DescriptorValueKind::Float, "rdkit:SurfacePolarity", "SurfacePolarity", "", "LabuteASA", "", 0u},
    {"PEOE_VSA1", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA1", "", 0u},
    {"PEOE_VSA10", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA10", "", 0u},
    {"PEOE_VSA11", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA11", "", 0u},
    {"PEOE_VSA12", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA12", "", 0u},
    {"PEOE_VSA13", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA13", "", 0u},
    {"PEOE_VSA14", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA14", "", 0u},
    {"PEOE_VSA2", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA2", "", 0u},
    {"PEOE_VSA3", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA3", "", 0u},
    {"PEOE_VSA4", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA4", "", 0u},
    {"PEOE_VSA5", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA5", "", 0u},
    {"PEOE_VSA6", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA6", "", 0u},
    {"PEOE_VSA7", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA7", "", 0u},
    {"PEOE_VSA8", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA8", "", 0u},
    {"PEOE_VSA9", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "PEOE_VSA9", "", 0u},
    {"SMR_VSA1", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA1", "", 0u},
    {"SMR_VSA10", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA10", "", 0u},
    {"SMR_VSA2", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA2", "", 0u},
    {"SMR_VSA3", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA3", "", 0u},
    {"SMR_VSA4", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA4", "", 0u},
    {"SMR_VSA5", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA5", "", 0u},
    {"SMR_VSA6", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA6", "", 0u},
    {"SMR_VSA7", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA7", "", 0u},
    {"SMR_VSA9", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SMR_VSA9", "", 0u},
    {"SlogP_VSA1", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA1", "", 0u},
    {"SlogP_VSA10", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA10", "", 0u},
    {"SlogP_VSA11", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA11", "", 0u},
    {"SlogP_VSA12", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA12", "", 0u},
    {"SlogP_VSA2", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA2", "", 0u},
    {"SlogP_VSA3", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA3", "", 0u},
    {"SlogP_VSA4", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA4", "", 0u},
    {"SlogP_VSA5", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA5", "", 0u},
    {"SlogP_VSA6", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA6", "", 0u},
    {"SlogP_VSA7", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA7", "", 0u},
    {"SlogP_VSA8", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "SlogP_VSA8", "", 0u},
    {"TPSA", DescriptorValueKind::Float, "rdkit:SurfacePolarity", "SurfacePolarity", "", "TPSA", "", 0u},
    {"EState_VSA1", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA1", "", 0u},
    {"EState_VSA10", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA10", "", 0u},
    {"EState_VSA2", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA2", "", 0u},
    {"EState_VSA3", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA3", "", 0u},
    {"EState_VSA4", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA4", "", 0u},
    {"EState_VSA5", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA5", "", 0u},
    {"EState_VSA6", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA6", "", 0u},
    {"EState_VSA7", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA7", "", 0u},
    {"EState_VSA8", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA8", "", 0u},
    {"EState_VSA9", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "EState_VSA9", "", 0u},
    {"VSA_EState1", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState1", "", 0u},
    {"VSA_EState10", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState10", "", 0u},
    {"VSA_EState2", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState2", "", 0u},
    {"VSA_EState3", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState3", "", 0u},
    {"VSA_EState4", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState4", "", 0u},
    {"VSA_EState5", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState5", "", 0u},
    {"VSA_EState6", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState6", "", 0u},
    {"VSA_EState7", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState7", "", 0u},
    {"VSA_EState8", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState8", "", 0u},
    {"VSA_EState9", DescriptorValueKind::Float, "rdkit:VSA", "VSA", "", "VSA_EState9", "", 0u},
    {"FractionCSP3", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "FractionCSP3", "", 0u},
    {"HeavyAtomCount", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "HeavyAtomCount", "quantity:heavy_atom_count", 0u},
    {"NHOHCount", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NHOHCount", "", 0u},
    {"NOCount", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NOCount", "", 0u},
    {"NumAliphaticCarbocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumAliphaticCarbocycles", "", 0u},
    {"NumAliphaticHeterocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumAliphaticHeterocycles", "", 0u},
    {"NumAliphaticRings", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumAliphaticRings", "", 0u},
    {"NumAmideBonds", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumAmideBonds", "", 0u},
    {"NumAromaticCarbocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumAromaticCarbocycles", "", 0u},
    {"NumAromaticHeterocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumAromaticHeterocycles", "", 0u},
    {"NumAromaticRings", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumAromaticRings", "", 0u},
    {"NumAtomStereoCenters", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumAtomStereoCenters", "", 0u},
    {"NumBridgeheadAtoms", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumBridgeheadAtoms", "", 0u},
    {"NumHAcceptors", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumHAcceptors", "", 0u},
    {"NumHDonors", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumHDonors", "", 0u},
    {"NumHeteroatoms", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumHeteroatoms", "", 0u},
    {"NumHeterocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumHeterocycles", "", 0u},
    {"NumRotatableBonds", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumRotatableBonds", "", 0u},
    {"NumSaturatedCarbocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumSaturatedCarbocycles", "", 0u},
    {"NumSaturatedHeterocycles", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumSaturatedHeterocycles", "", 0u},
    {"NumSaturatedRings", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "NumSaturatedRings", "", 0u},
    {"NumSpiroAtoms", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumSpiroAtoms", "", 0u},
    {"NumUnspecifiedAtomStereoCenters", DescriptorValueKind::Int, "rdkit:CountsWeights", "CountsWeights", "", "NumUnspecifiedAtomStereoCenters", "", 0u},
    {"Phi", DescriptorValueKind::Float, "rdkit:CountsWeights", "CountsWeights", "", "Phi", "", 0u},
    {"RingCount", DescriptorValueKind::Int, "rdkit:RingCounts", "RingCounts", "", "RingCount", "", 0u},
    {"MolLogP", DescriptorValueKind::Float, "rdkit:Crippen", "Crippen", "", "MolLogP", "", 0u},
    {"MolMR", DescriptorValueKind::Float, "rdkit:Crippen", "Crippen", "", "MolMR", "", 0u},
    {"fr_Al_COO", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Al_COO", "", 0u},
    {"fr_Al_OH", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Al_OH", "", 0u},
    {"fr_Al_OH_noTert", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Al_OH_noTert", "", 0u},
    {"fr_ArN", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_ArN", "", 0u},
    {"fr_Ar_COO", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Ar_COO", "", 0u},
    {"fr_Ar_N", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Ar_N", "", 0u},
    {"fr_Ar_NH", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Ar_NH", "", 0u},
    {"fr_Ar_OH", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Ar_OH", "", 0u},
    {"fr_COO", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_COO", "", 0u},
    {"fr_COO2", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_COO2", "", 0u},
    {"fr_C_O", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_C_O", "", 0u},
    {"fr_C_O_noCOO", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_C_O_noCOO", "", 0u},
    {"fr_C_S", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_C_S", "", 0u},
    {"fr_HOCCN", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_HOCCN", "", 0u},
    {"fr_Imine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Imine", "", 0u},
    {"fr_NH0", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_NH0", "", 0u},
    {"fr_NH1", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_NH1", "", 0u},
    {"fr_NH2", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_NH2", "", 0u},
    {"fr_N_O", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_N_O", "", 0u},
    {"fr_Ndealkylation1", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Ndealkylation1", "", 0u},
    {"fr_Ndealkylation2", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Ndealkylation2", "", 0u},
    {"fr_Nhpyrrole", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_Nhpyrrole", "", 0u},
    {"fr_SH", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_SH", "", 0u},
    {"fr_aldehyde", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_aldehyde", "", 0u},
    {"fr_alkyl_carbamate", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_alkyl_carbamate", "", 0u},
    {"fr_alkyl_halide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_alkyl_halide", "", 0u},
    {"fr_allylic_oxid", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_allylic_oxid", "", 0u},
    {"fr_amide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_amide", "", 0u},
    {"fr_amidine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_amidine", "", 0u},
    {"fr_aniline", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_aniline", "", 0u},
    {"fr_aryl_methyl", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_aryl_methyl", "", 0u},
    {"fr_azide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_azide", "", 0u},
    {"fr_azo", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_azo", "", 0u},
    {"fr_barbitur", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_barbitur", "", 0u},
    {"fr_benzene", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_benzene", "", 0u},
    {"fr_benzodiazepine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_benzodiazepine", "", 0u},
    {"fr_bicyclic", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_bicyclic", "", 0u},
    {"fr_diazo", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_diazo", "", 0u},
    {"fr_dihydropyridine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_dihydropyridine", "", 0u},
    {"fr_epoxide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_epoxide", "", 0u},
    {"fr_ester", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_ester", "", 0u},
    {"fr_ether", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_ether", "", 0u},
    {"fr_furan", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_furan", "", 0u},
    {"fr_guanido", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_guanido", "", 0u},
    {"fr_halogen", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_halogen", "", 0u},
    {"fr_hdrzine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_hdrzine", "", 0u},
    {"fr_hdrzone", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_hdrzone", "", 0u},
    {"fr_imidazole", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_imidazole", "", 0u},
    {"fr_imide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_imide", "", 0u},
    {"fr_isocyan", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_isocyan", "", 0u},
    {"fr_isothiocyan", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_isothiocyan", "", 0u},
    {"fr_ketone", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_ketone", "", 0u},
    {"fr_ketone_Topliss", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_ketone_Topliss", "", 0u},
    {"fr_lactam", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_lactam", "", 0u},
    {"fr_lactone", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_lactone", "", 0u},
    {"fr_methoxy", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_methoxy", "", 0u},
    {"fr_morpholine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_morpholine", "", 0u},
    {"fr_nitrile", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_nitrile", "", 0u},
    {"fr_nitro", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_nitro", "", 0u},
    {"fr_nitro_arom", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_nitro_arom", "", 0u},
    {"fr_nitro_arom_nonortho", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_nitro_arom_nonortho", "", 0u},
    {"fr_nitroso", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_nitroso", "", 0u},
    {"fr_oxazole", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_oxazole", "", 0u},
    {"fr_oxime", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_oxime", "", 0u},
    {"fr_para_hydroxylation", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_para_hydroxylation", "", 0u},
    {"fr_phenol", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_phenol", "", 0u},
    {"fr_phenol_noOrthoHbond", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_phenol_noOrthoHbond", "", 0u},
    {"fr_phos_acid", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_phos_acid", "", 0u},
    {"fr_phos_ester", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_phos_ester", "", 0u},
    {"fr_piperdine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_piperdine", "", 0u},
    {"fr_piperzine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_piperzine", "", 0u},
    {"fr_priamide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_priamide", "", 0u},
    {"fr_prisulfonamd", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_prisulfonamd", "", 0u},
    {"fr_pyridine", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_pyridine", "", 0u},
    {"fr_quatN", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_quatN", "", 0u},
    {"fr_sulfide", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_sulfide", "", 0u},
    {"fr_sulfonamd", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_sulfonamd", "", 0u},
    {"fr_sulfone", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_sulfone", "", 0u},
    {"fr_term_acetylene", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_term_acetylene", "", 0u},
    {"fr_tetrazole", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_tetrazole", "", 0u},
    {"fr_thiazole", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_thiazole", "", 0u},
    {"fr_thiocyan", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_thiocyan", "", 0u},
    {"fr_thiophene", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_thiophene", "", 0u},
    {"fr_unbrch_alkane", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_unbrch_alkane", "", 0u},
    {"fr_urea", DescriptorValueKind::Int, "rdkit:Fragments", "Fragments", "", "fr_urea", "", 0u},
}};

} // namespace

std::shared_ptr<const DescriptorSchema> RDKitDescriptorSchema() {
    static const std::shared_ptr<const DescriptorSchema> schema = [] {
        std::vector<DescriptorDefinition> definitions;
        definitions.reserve(kRDKitDefinitions.size());
        for (const auto& item : kRDKitDefinitions) {
            DescriptorDefinition definition;
            definition.name = item.name;
            definition.value_kind = item.value_kind;
            definition.group = item.group;
            definition.source_name = "RDKit";
            definition.source_type = item.source_type;
            definition.source_version = "RDKit-2026.03.3";
            definition.parameters = item.parameters;
            definition.description = item.description;
            definition.canonical_id = item.canonical_id;
            definition.prerequisites = item.prerequisites;
            definitions.push_back(std::move(definition));
        }
        return std::make_shared<const DescriptorSchema>(std::move(definitions));
    }();
    return schema;
}

} // namespace OEFP
